apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp
  namespace: todoapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todolist
  template:
    metadata:
      labels:
        app: todolist
    spec:
      containers:
        - name: todoapp
          image: ikulyk404/todoapp:3.0.0
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: todolist.settings
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
